-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: May 04, 2015 at 12:36 AM
-- Server version: 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `integradb`
--

-- --------------------------------------------------------

--
-- Table structure for table `flpmu_modules`
--

CREATE TABLE IF NOT EXISTS `flpmu_modules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `asset_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'FK to the #__assets table.',
  `title` varchar(100) NOT NULL DEFAULT '',
  `note` varchar(255) NOT NULL DEFAULT '',
  `content` text NOT NULL,
  `ordering` int(11) NOT NULL DEFAULT '0',
  `position` varchar(50) NOT NULL DEFAULT '',
  `checked_out` int(10) unsigned NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `published` tinyint(1) NOT NULL DEFAULT '0',
  `module` varchar(50) DEFAULT NULL,
  `access` int(10) unsigned NOT NULL DEFAULT '0',
  `showtitle` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `params` text NOT NULL,
  `client_id` tinyint(4) NOT NULL DEFAULT '0',
  `language` char(7) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `published` (`published`,`access`),
  KEY `newsfeeds` (`module`,`published`),
  KEY `idx_language` (`language`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=156 ;

--
-- Dumping data for table `flpmu_modules`
--

INSERT INTO `flpmu_modules` (`id`, `asset_id`, `title`, `note`, `content`, `ordering`, `position`, `checked_out`, `checked_out_time`, `publish_up`, `publish_down`, `published`, `module`, `access`, `showtitle`, `params`, `client_id`, `language`) VALUES
(1, 96, 'Main Menu', '', '', 1, 'menu', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_menu', 1, 0, '{"menutype":"mainmenu","active":"","startLevel":"1","endLevel":"0","showAllChildren":"1","tag_id":"","class_sfx":"","window_open":"","layout":"_:default","moduleclass_sfx":"_menu","cache":"1","cache_time":"900","cachemode":"itemid","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(2, 0, 'Login', '', '', 1, 'login', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_login', 1, 1, '', 1, '*'),
(3, 0, 'Popular Articles', '', '', 3, 'cpanel', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_popular', 3, 1, '{"count":"5","catid":"","user_id":"0","layout":"_:default","moduleclass_sfx":"","cache":"0","automatic_title":"1"}', 1, '*'),
(4, 0, 'Recently Added Articles', '', '', 4, 'cpanel', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_latest', 3, 1, '{"count":"5","ordering":"c_dsc","catid":"","user_id":"0","layout":"_:default","moduleclass_sfx":"","cache":"0","automatic_title":"1"}', 1, '*'),
(8, 0, 'Toolbar', '', '', 1, 'toolbar', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_toolbar', 3, 1, '', 1, '*'),
(9, 0, 'Quick Icons', '', '', 1, 'icon', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_quickicon', 3, 1, '', 1, '*'),
(10, 0, 'Logged-in Users', '', '', 2, 'cpanel', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_logged', 3, 1, '{"count":"5","name":"1","layout":"_:default","moduleclass_sfx":"","cache":"0","automatic_title":"1"}', 1, '*'),
(12, 0, 'Admin Menu', '', '', 1, 'menu', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_menu', 3, 1, '{"layout":"","moduleclass_sfx":"","shownew":"1","showhelp":"1","cache":"0"}', 1, '*'),
(13, 0, 'Admin Submenu', '', '', 1, 'submenu', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_submenu', 3, 1, '', 1, '*'),
(14, 0, 'User Status', '', '', 2, 'status', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_status', 3, 1, '', 1, '*'),
(15, 0, 'Title', '', '', 1, 'title', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_title', 3, 1, '', 1, '*'),
(16, 0, 'Login Form', '', '', 7, 'position-7', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_login', 1, 1, '{"greeting":"1","name":"0"}', 0, '*'),
(17, 0, 'Breadcrumbs', '', '', 1, 'position-2', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_breadcrumbs', 1, 1, '{"moduleclass_sfx":"","showHome":"1","homeText":"Home","showComponent":"1","separator":"","cache":"1","cache_time":"900","cachemode":"itemid"}', 0, '*'),
(79, 0, 'Multilanguage status', '', '', 1, 'status', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_multilangstatus', 3, 1, '{"layout":"_:default","moduleclass_sfx":"","cache":"0"}', 1, '*'),
(80, 0, 'Author Menu', '', '', 1, 'position-1', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_menu', 3, 0, '{"menutype":"authormenu","startLevel":"1","endLevel":"0","showAllChildren":"0","tag_id":"","class_sfx":" nav-pills","window_open":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"itemid"}', 0, '*'),
(81, 0, 'Blog Roll', '', '', 3, 'position-7', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_weblinks', 1, 1, '{"catid":"8","count":"5","ordering":"title","direction":"asc","target":"1","description":"0","hits":"0","count_clicks":"0","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static"}', 0, '*'),
(82, 0, 'Syndication', '', '', 6, 'position-7', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_syndicate', 1, 0, '{"display_text":1,"text":"My Blog","format":"rss","layout":"_:default","moduleclass_sfx":"","cache":"0"}', 0, '*'),
(83, 0, 'Archived Articles', '', '', 4, 'position-7', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_articles_archive', 1, 1, '{"count":"10","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static"}', 0, '*'),
(84, 0, 'Most Read Posts', '', '', 5, 'position-7', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_articles_popular', 1, 1, '{"catid":["9"],"count":"5","show_front":"1","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static"}', 0, '*'),
(85, 0, 'Older Posts', '', '', 2, 'position-7', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_articles_category', 1, 1, '{"mode":"normal","show_on_article_page":"0","show_front":"show","count":"6","category_filtering_type":"1","catid":["9"],"show_child_category_articles":"0","levels":"1","author_filtering_type":"1","created_by":[""],"author_alias_filtering_type":"1","created_by_alias":[""],"excluded_articles":"","date_filtering":"off","date_field":"a.created","start_date_range":"","end_date_range":"","relative_date":"30","article_ordering":"a.created","article_ordering_direction":"DESC","article_grouping":"none","article_grouping_direction":"krsort","month_year_format":"F Y","item_heading":"5","link_titles":"1","show_date":"0","show_date_field":"created","show_date_format":"Y-m-d H:i:s","show_category":"0","show_hits":"0","show_author":"0","show_introtext":"0","introtext_limit":"100","show_readmore":"0","show_readmore_title":"1","readmore_limit":"15","layout":"_:default","moduleclass_sfx":"","owncache":"1","cache_time":"900","module_tag":"div","bootstrap_size":"1","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(86, 0, 'Bottom Menu', '', '', 8, 'position-7', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_menu', 1, 0, '{"menutype":"bottommenu","startLevel":"1","endLevel":"0","showAllChildren":"0","tag_id":"","class_sfx":"","window_open":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"itemid"}', 0, '*'),
(87, 0, 'Search', '', '', 1, 'position-0', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_search', 1, 1, '{"label":"","width":"20","text":"","button":"","button_pos":"right","imagebutton":"","button_text":"","opensearch":"1","opensearch_title":"","set_itemid":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"itemid"}', 0, '*'),
(88, 0, 'Image', '', '<p><img src="images/headers/raindrops.jpg" alt="" /></p>', 1, 'position-3', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 0, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"1","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(89, 87, 'Footer menu', '', '', 1, 'footer', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_menu', 1, 0, '{"menutype":"mainmenu","base":"","startLevel":"1","endLevel":"1","showAllChildren":"0","tag_id":"","class_sfx":"","window_open":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"itemid","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(90, 80, '[icon-ok] Weblinks', '', '<ul>\r\n<li><a href="http://www.gavick.com">Joomla! 3.0 Templates</a></li>\r\n<li><a href="http://www.gavick.com/forums">Support forum</a></li>\r\n<li><a href="http://www.gavick.com/documentation">Documentation</a></li>\r\n<li><a href="http://www.gavick.com/magazine">GavickPro Blog</a></li>\r\n<li><a href="http://github.com/GavickPro">GavickPro on Github</a></li>\r\n</ul>', 0, 'bottom', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(91, 81, '[icon-fire] Hot links', '', '<ul>\r\n<li><a href="http://demo.gavick.com">Joomla! Templates</a></li>\r\n<li><a href="http://demo.gavick.com/joomla16/jun2012/">Bikestore</a></li>\r\n<li><a href="http://demo.gavick.com/free/may2012/">Music Free</a></li>\r\n<li><a href="http://demo.gavick.com/joomla16/may2012">Fashion</a></li>\r\n<li><a href="https://www.gavick.com/joomla-templates.html">Our portfolio</a></li>\r\n</ul>', 0, 'bottom', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(92, 82, '[icon-time] Templates', '', '<ul>\r\n<li><a href="http://www.gavick.com/joomla-templates/responsive-ecommerce-virtuemart-joomla-template,92.html">Bikestore</a></li>\r\n<li><a href="http://www.gavick.com/joomla-templates/free-responsive-joomla-template,91.html">Music Free</a></li>\r\n<li><a href="http://www.gavick.com/joomla-templates/fashion,90.html">Fashion</a></li>\r\n<li><a href="http://www.gavick.com/joomla-templates/restaurant,88.html">Restaurant</a></li>\r\n<li><a href="http://www.gavick.com/joomla-templates/appspro-tech,87.html">AppsProTech</a></li>\r\n</ul>', 0, 'bottom', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(93, 83, '[icon-gift] Freebies', '', '<ul>\r\n<li><a href="http://www.gavick.com/magazine/dream-flower-free-portfolio-psd-template.html">Dream Flower</a></li>\r\n<li><a href="http://www.gavick.com/magazine/free-portfolio-and-blog-psd-template.html">Free Portfolio</a></li>\r\n<li><a href="http://www.gavick.com/magazine/roberto-%7C-free-psd-template.html">Roberto</a></li>\r\n<li><a href="http://www.gavick.com/magazine/gasolina-awesome-free-psd-template.html">Gasolina</a></li>\r\n<li><a href="http://www.gavick.com/magazine/trybokeh-fancybg-and-yellowfun-free-blog-psd-templates.html">Trybokeh</a></li>\r\n</ul>', 0, 'bottom', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(94, 84, '[icon-exclamation-sign] Important', '', '<ul>\r\n<li><a href="http://www.gavick.com/updates.html">Updates</a></li>\r\n<li><a href="http://www.gavick.com/affiliate/">Affiliates</a></li>\r\n<li><a href="http://www.gavick.com/supportdesk/index.php?/Tickets/Submit">Help desk</a></li>\r\n<li><a href="http://validate.gavick.com/">Validate license</a></li>\r\n<li><a href="http://www.gavick.com/supportdesk/index.php?/Tickets/Submit">Contact</a></li>\r\n</ul>', 0, 'bottom', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(95, 85, '[icon-thumbs-up] Share ', '', '<ul>\r\n<li><a href="http://www.facebook.com/gavickpro">Facebook</a></li>\r\n<li><a href="http://twitter.com/gavickpro">Twitter</a></li>\r\n<li><a href="http://www.gavick.com/magazine/index.php?format=feed&amp;type=rss">RSS</a></li>\r\n<li><a href="https://plus.google.com/110937149959405490547?prsrc=3">Google+</a></li>\r\n<li><a href="http://github.com/GavickPro">Github</a></li>\r\n</ul>', 0, 'bottom', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(96, 88, 'Header - frontpage', '', '<h1 class="gk-big-header">Hello, integradora!</h1>\r\n<h2 class="gk-small-header">Espero desarrollarme muy rápido, para que puedan usarme como plataforma que automatiza los procesos de sus integrados y su operación.</h2>\r\n<p class="gk-buttons"><a class="gk-blue-button" href="index.php/template/content/single-article">Más detalles</a> <a id="gk-download-btn" class="gk-yellow-button" title="Coming soon…" href="#coming-soon">Próximamente</a></p>', 1, 'header', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(97, 89, 'HEADER - module variations', '', '<h1 class="gk-medium-header">Template Module Variations</h1>', 0, 'header', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(98, 90, 'Header - module positions', '', '<h1 class="gk-medium-header">Template Module Positions</h1>', 0, 'header', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(99, 91, 'Header - Typography', '', '<h1 class="gk-medium-header">Template Typography</h1>', 0, 'header', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(100, 93, 'Based on Bootstrap', '', '<div class="container-fluid">\r\n<div class="row-fluid">\r\n<div class="span4 gk-demo-content"><img src="templates/meet_gavern/images/content/joomla30.png" alt="Free Joomla! 3.0 Template" />\r\n<h2>Free Joomla! 3.0 Template</h2>\r\n<p>This is our first and free template built especially for Joomla 3.0. Want to know more about Joomla 3.0?</p>\r\n<a class="btn btn-large" href="http://www.joomla.org/3/">Read more</a></div>\r\n<div class="span4 gk-demo-content"><img src="templates/meet_gavern/images/content/gavern_plus_bootstrap.png" alt="Gavern + Bootstrap" />\r\n<h2>Gavern + Bootstrap</h2>\r\n<p>Meet Gavern is based upon a brand new version of the Gavern Framework which features built-in support for Bootstrap</p>\r\n<a class="btn btn-large" href="index.php/template/content/single-article">Read more</a></div>\r\n<div class="span4 gk-demo-content"><img src="templates/meet_gavern/images/content/responsive_design.png" alt="Responsive Web Design" />\r\n<h2>Responsive Web Design</h2>\r\n<p>Joomla! 3.0 and Gavern Framework are prepared to support Responsive Web Design</p>\r\n<a class="btn btn-large" href="http://gavick.com/magazine/responsive-web-design-necessity-or-fashion.html">Read more</a></div>\r\n</div>\r\n</div>', 1, 'mainbody', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 0, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(101, 106, 'Social icons', '', '<p><a class="gk-facebook-icon" href="http://www.facebook.com/gavickpro">Facebook</a><a class="gk-gplus-icon" href="https://plus.google.com/110937149959405490547?prsrc=3">G+</a><a class="gk-twitter-icon" href="http://twitter.com/gavickpro">Twitter</a><a class="gk-rss-icon" href="http://www.gavick.com/magazine/index.php?format=feed&amp;type=rss">RSS</a></p>', 0, 'social', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(102, 86, 'Breadcrumbs', '', '', 0, 'breadcrumb', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_breadcrumbs', 1, 1, '{"showHere":"1","showHome":"1","homeText":"","showLast":"1","separator":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"itemid","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(103, 98, '[icon-search] Search', '', '', 1, 'sidebar', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_search', 1, 1, '{"label":"","width":"20","text":"","button":"","button_pos":"right","imagebutton":"","button_text":"","opensearch":"1","opensearch_title":"","set_itemid":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"itemid","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(104, 107, 'Suffix default', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(105, 108, 'Suffix "blue"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(106, 109, 'Suffix "blue-header"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue-header","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(107, 110, 'Suffix "red"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"red","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(108, 99, 'Latest News', '', '', 1, 'sidebar', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_articles_latest', 1, 1, '{"catid":[""],"count":"5","show_featured":"","ordering":"c_dsc","user_id":"0","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(109, 92, 'Log in', '', '', 1, 'login', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_login', 1, 1, '{"pretext":"","posttext":"","login":"","logout":"","greeting":"1","name":"0","usesecure":"0","usetext":"0","layout":"_:default","moduleclass_sfx":"","cache":"0","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(110, 0, 'Suffix "red-header"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"red-header","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(111, 0, 'Suffix "blue" (2)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(112, 0, 'Suffix "blue-header" (2)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue-header","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(113, 0, 'Suffix "red" (2)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"red","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(114, 0, 'Suffix default (3)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(115, 0, 'Suffix "blue" (3)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(116, 0, 'Suffix "blue-header" (3)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue-header","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(117, 0, 'Suffix "red" (3)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"red","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(118, 0, 'Suffix default (4)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(119, 0, 'Suffix "blue" (4)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(120, 0, 'Suffix "blue-header" (4)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue-header","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(121, 0, 'Suffix "red" (4)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"red","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(122, 0, 'Suffix default (5)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(123, 0, 'Suffix "blue" (5)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(124, 0, 'Suffix "blue-header" (5)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue-header","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(125, 0, 'Suffix "red" (5)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"red","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(126, 0, 'Suffix default (6)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(127, 0, 'Suffix "blue" (6)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(128, 0, 'Suffix "blue-header" (6)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"blue-header","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(129, 0, 'Suffix "red" (6)', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', -2, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"red","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*'),
(130, 111, 'Suffix "red-header"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"red-header","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(131, 112, 'Suffix "green"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"green","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(132, 113, 'Suffix "green-header"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"green-header","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(133, 114, 'Suffix "yellow"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"yellow","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(134, 115, 'Suffix "yellow-header"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"yellow-header","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(135, 116, 'Suffix "border1"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"border1","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(136, 117, 'Suffix "border2"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"border2","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(137, 118, 'Suffix "border3"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"border3","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(138, 119, 'Suffix "hot"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"hot","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(139, 120, 'Suffix "popular"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"popular","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(140, 121, 'Suffix "new"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"new","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(141, 122, 'Suffix "coming"', '', '<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.</p>\r\n<ul>\r\n<li><a href="#">Donec id elit non mi porta.</a></li>\r\n<li><a href="#">Gravida at eget metus.</a></li>\r\n<li><a href="#">Praesent commodo cursus</a></li>\r\n<li><a href="#">Magna, vel scelerisque</a></li>\r\n</ul>', 1, 'top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_custom', 1, 1, '{"prepare_content":"1","backgroundimage":"","layout":"_:default","moduleclass_sfx":"coming","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(152, 94, 'Mainbody modules Test', '', 'Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Donec sed odio dui. Curabitur blandit tempus porttitor.\r\n\r\nAenean lacinia bibendum nulla sed consectetur. Donec ullamcorper nulla non metus auctor fringilla. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.', 1, 'mainbody_top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_custom', 1, 1, '{"prepare_content":"0","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(153, 95, 'Mainbody modules Test (2)', '', 'Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Donec sed odio dui. Curabitur blandit tempus porttitor.\r\n\r\nAenean lacinia bibendum nulla sed consectetur. Donec ullamcorper nulla non metus auctor fringilla. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.', 1, 'mainbody_top', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_custom', 1, 1, '{"prepare_content":"0","backgroundimage":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(154, 97, 'Login', '', '', 1, 'sidebar', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'mod_login', 1, 1, '{"pretext":"","posttext":"","login":"","logout":"","greeting":"1","name":"0","usesecure":"0","usetext":"0","layout":"_:default","moduleclass_sfx":"","cache":"0","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB'),
(155, 123, 'Usermenu', '', '', 1, 'usermenu', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_menu', 2, 0, '{"menutype":"authormenu","base":"","startLevel":"1","endLevel":"1","showAllChildren":"1","tag_id":"","class_sfx":"","window_open":"","layout":"_:default","moduleclass_sfx":"","cache":"1","cache_time":"900","cachemode":"itemid","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, 'en-GB');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
